#!/usr/bin/env python3
"""
Measure instruction timing from the protected-mode instruction_timing benchmark.

This script reads the VCD generated by:

    ./test_protected_mode.py instruction_timing --trace

and prints per-phase timing stats in cycles. With --run, it will regenerate the
trace first by invoking the protected-mode test runner.
"""

from __future__ import annotations

import argparse
import os
import statistics
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


TEST_NAME = "instruction_timing"
TESTS_DIR = Path(__file__).resolve().parent
DEFAULT_TRACE = TESTS_DIR / "protected_mode_tests" / "traces" / f"{TEST_NAME}.vcd"

SIGNALS = {
    "clk": "TOP.tb_protected_mode.clk",
    "eip": "TOP.tb_protected_mode.dut.EIP",
    "i_first": "TOP.tb_protected_mode.dut.i_first",
}


@dataclass(frozen=True)
class SteadyPhase:
    name: str
    description: str
    target_cycles: float
    eips: tuple[int, ...]


@dataclass(frozen=True)
class BranchPhase:
    name: str
    description: str
    target_cycles: float
    branch_eip: int
    target_eip: int


@dataclass(frozen=True)
class PhaseResult:
    name: str
    description: str
    target_cycles: float
    samples: tuple[float, ...]
    branch: bool = False


STEADY_PHASES = [
    SteadyPhase("load", "mov eax, [esi]", 4.0, (0x10D, 0x10F, 0x111, 0x113, 0x115, 0x117, 0x119, 0x11B)),
    SteadyPhase("store", "mov [edi], eax", 2.0, (0x20C, 0x20E, 0x210, 0x212, 0x214, 0x216, 0x218, 0x21A)),
    SteadyPhase("push_reg_to_mem", "push eax", 2.0, (0x30B, 0x30C, 0x30D, 0x30E, 0x30F, 0x310, 0x311, 0x312)),
    SteadyPhase("move_reg_to_reg", "mov eax, ebx", 2.0, (0x409, 0x40B, 0x40D, 0x40F, 0x411, 0x413, 0x415, 0x417)),
    SteadyPhase("load_immediate", "mov eax, imm32", 2.0, (0x507, 0x50C, 0x511, 0x516, 0x51B, 0x520, 0x525, 0x52A)),
    SteadyPhase("alu_reg_to_reg", "add eax, ebx", 2.0, (0x609, 0x60B, 0x60D, 0x60F, 0x611, 0x613, 0x615, 0x617)),
    SteadyPhase("pop_mem_to_reg", "pop eax", 4.0, (0x74A, 0x74B, 0x74C, 0x74D, 0x74E, 0x74F, 0x750, 0x751)),
    SteadyPhase("conditional_jump_not_taken", "jnz not-taken forward", 3.0, (0x804, 0x806, 0x808, 0x80A, 0x80C, 0x80E, 0x810, 0x812)),
    SteadyPhase("conditional_jump_not_taken_back", "jnz not-taken backward", 3.0, (0x150D, 0x150F, 0x1511, 0x1513, 0x1515, 0x1517, 0x1519, 0x151B)),
    SteadyPhase("conditional_jump_taken_fwd", "jnz taken forward", 9.25, (0x140B, 0x140E, 0x1411, 0x1414, 0x1417, 0x141A, 0x141D, 0x1420)),
    SteadyPhase("lea", "lea eax, [esi+edi*4+0x20]", 2.0, (0xB0E, 0xB12, 0xB16, 0xB1A, 0xB1E, 0xB22, 0xB26, 0xB2A)),
    SteadyPhase("rotate_reg_cl", "rol eax, cl", 3.0, (0xC0C, 0xC0E, 0xC10, 0xC12, 0xC14, 0xC16, 0xC18, 0xC1A)),
    SteadyPhase("xchg_reg_reg", "xchg ecx, ebx", 3.0, (0xD0C, 0xD0E, 0xD10, 0xD12, 0xD14, 0xD16, 0xD18, 0xD1A)),
    SteadyPhase("xchg_mem_reg", "xchg [edi], eax", 5.0, (0xE12, 0xE14, 0xE16, 0xE18, 0xE1A, 0xE1C, 0xE1E, 0xE20)),
    SteadyPhase("push_imm_to_mem", "push imm32", 2.0, (0xF0A, 0xF0F, 0xF14, 0xF19, 0xF1E, 0xF23, 0xF28, 0xF2D)),
    SteadyPhase("push_seg_to_mem", "push ds", 2.0, (0x1006, 0x1007, 0x1008, 0x1009, 0x100A, 0x100B, 0x100C, 0x100D)),
    SteadyPhase("push_mem_to_mem", "push dword [esi]", 5.0, (0x1112, 0x1114, 0x1116, 0x1118, 0x111A, 0x111C, 0x111E, 0x1120)),
    SteadyPhase("pop_mem_to_mem", "pop dword [edi]", 5.0, (0x1282, 0x1284, 0x1286, 0x1288, 0x128A, 0x128C, 0x128E, 0x1290)),
    SteadyPhase("alu_reg_mem", "add eax, [esi]", 5.0, (0x130F, 0x1311, 0x1313, 0x1315, 0x1317, 0x1319, 0x131B, 0x131D)),
    # DOOM render-loop dominant types (see doc/0.4/doom.md).
    SteadyPhase("byte_load", "mov al, [esi]", 4.0, (0x170A, 0x170C, 0x170E, 0x1710, 0x1712, 0x1714, 0x1716, 0x1718)),
    SteadyPhase("byte_store", "mov [edi], al", 2.0, (0x180A, 0x180C, 0x180E, 0x1810, 0x1812, 0x1814, 0x1816, 0x1818)),
    SteadyPhase("shift_reg_imm", "shr eax, 4", 3.0, (0x1905, 0x1908, 0x190B, 0x190E, 0x1911, 0x1914, 0x1917, 0x191A)),
    SteadyPhase("alu_reg_imm", "cmp ebx, imm32", 2.0, (0x1A05, 0x1A0B, 0x1A11, 0x1A17, 0x1A1D, 0x1A23, 0x1A29, 0x1A2F)),
    # rep movsb of REP_COUNT(64) bytes + 3-mov ESI/EDI/ECX reset per copy.
    # 80386 ref ~ 5 + 4*count; 64B ~= 261.  z386 currently ~333 (~5.2 cyc/byte).
    SteadyPhase("rep_movsb", "rep movsb (64B)", 261.0, (0x1B10, 0x1B21, 0x1B32, 0x1B43, 0x1B54, 0x1B65, 0x1B76, 0x1B87)),
]

BRANCH_PHASES = [
    BranchPhase("conditional_jump_taken", "jnz taken backward", 9.25, branch_eip=0x90D, target_eip=0x90A),
    BranchPhase("unconditional_jump", "jmp taken backward", 9.25, branch_eip=0xA0F, target_eip=0xA0A),
    BranchPhase("call_taken", "call taken", 9.25, branch_eip=0x1611, target_eip=0x1619),
]


# Best-case z386 0.1 baseline from doc/early-start.md.  These are constants so
# the timing script can show progress against the documented starting point.
Z386_01_MIN_CYCLES = {
    "move_reg_to_reg": 2.0,
    "alu_reg_to_reg": 2.0,
    "rotate_reg_cl": 3.0,
    "xchg_reg_reg": 3.0,
    "conditional_jump_not_taken": 3.0,
    "load": 7.0,
    "store": 5.0,
    "push_reg_to_mem": 5.0,
    "pop_mem_to_reg": 6.0,
    "lea": 4.0,
    "xchg_mem_reg": 11.0,
    "push_imm_to_mem": 6.0,
    "push_seg_to_mem": 5.0,
    "push_mem_to_mem": 11.0,
    "pop_mem_to_mem": 11.0,
    "conditional_jump_taken": 12.0,
    "unconditional_jump": 9.0,
    "load_immediate": 3.0,
}


def parse_bit_value(raw: str) -> int | None:
    raw = raw.strip().lower()
    if not raw:
        return None
    if any(ch in raw for ch in "xzuwlh-"):
        return None
    return int(raw, 2)


def parse_vcd_header(vcd_path: Path) -> tuple[dict[str, str], dict[str, str]]:
    id_to_name: dict[str, str] = {}
    name_to_id: dict[str, str] = {}
    scope_stack: list[str] = []

    with vcd_path.open(errors="replace") as f:
        for raw_line in f:
            line = raw_line.strip()
            if line.startswith("$scope "):
                parts = line.split()
                if len(parts) >= 3:
                    scope_stack.append(parts[2])
                continue
            if line.startswith("$upscope"):
                if scope_stack:
                    scope_stack.pop()
                continue
            if line.startswith("$var "):
                parts = line.split()
                if len(parts) >= 5:
                    sig_id = parts[3]
                    name = parts[4]
                    full_name = ".".join(scope_stack + [name])
                    id_to_name[sig_id] = full_name
                    name_to_id[full_name] = sig_id
                continue
            if line.startswith("$enddefinitions"):
                break

    return id_to_name, name_to_id


def apply_changes(
    time_value: int,
    changes: dict[str, str],
    state: dict[str, str],
    ids: dict[str, str],
    clk_rises: list[int],
    i_first_events: list[tuple[int, int]],
) -> None:
    if not changes:
        return

    prev_values = {sig_id: state.get(sig_id) for sig_id in changes}
    state.update(changes)

    clk_id = ids["clk"]
    if clk_id in changes and prev_values.get(clk_id) == "0" and state.get(clk_id) == "1":
        clk_rises.append(time_value)

    eip_id = ids["eip"]
    i_first_id = ids["i_first"]
    eip_value = parse_bit_value(state.get(eip_id, ""))
    if (
        i_first_id in changes
        and prev_values.get(i_first_id) == "0"
        and state.get(i_first_id) == "1"
        and eip_value is not None
    ):
        i_first_events.append((time_value, eip_value))


def parse_trace(vcd_path: Path) -> tuple[list[int], list[tuple[int, int]]]:
    _id_to_name, name_to_id = parse_vcd_header(vcd_path)

    missing = [name for name in SIGNALS.values() if name not in name_to_id]
    if missing:
        raise SystemExit(f"Missing signals in {vcd_path}: {missing}")

    ids = {key: name_to_id[name] for key, name in SIGNALS.items()}
    selected_ids = set(ids.values())

    clk_rises: list[int] = []
    i_first_events: list[tuple[int, int]] = []

    state: dict[str, str] = {}
    current_time = 0
    changes: dict[str, str] = {}
    in_header = True

    with vcd_path.open(errors="replace") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line:
                continue

            if in_header:
                if line.startswith("$enddefinitions"):
                    in_header = False
                continue

            if line[0] == "#":
                apply_changes(current_time, changes, state, ids, clk_rises, i_first_events)
                changes = {}
                current_time = int(line[1:])
                continue

            if line[0] == "$":
                continue

            if line[0] in "01xXzZ":
                sig_id = line[1:]
                if sig_id in selected_ids:
                    changes[sig_id] = line[0].lower()
                continue

            if line[0] == "b":
                parts = line.split()
                if len(parts) == 2 and parts[1] in selected_ids:
                    changes[parts[1]] = parts[0][1:].lower()
                continue

    apply_changes(current_time, changes, state, ids, clk_rises, i_first_events)
    return clk_rises, i_first_events


def infer_cycle_period(clk_rises: list[int]) -> float:
    if len(clk_rises) < 3:
        raise SystemExit("Not enough clock edges to infer cycle period")
    deltas = [b - a for a, b in zip(clk_rises, clk_rises[1:])]
    return statistics.median(deltas[: min(16, len(deltas))])


def cycles(delta_time: int, cycle_period: float) -> float:
    return delta_time / cycle_period


def summarize(values: list[float]) -> str:
    if not values:
        return "n/a"
    avg = statistics.mean(values)
    lo = min(values)
    hi = max(values)
    return f"avg {avg:.1f}, min {lo:.1f}, max {hi:.1f}"


def fmt_cycles(value: float | None) -> str:
    if value is None:
        return "-"
    if abs(value - round(value)) < 0.005:
        return f"{round(value):.0f}"
    if abs(value * 10 - round(value * 10)) < 0.005:
        return f"{value:.1f}"
    return f"{value:.2f}"


def format_table_row(columns: list[str], widths: list[int]) -> str:
    cells = []
    for index, (column, width) in enumerate(zip(columns, widths)):
        if index == 0:
            cells.append(column.ljust(width))
        else:
            cells.append(column.rjust(width))
    return "| " + " | ".join(cells) + " |"


def print_comparison_table(results: list[PhaseResult], color_enabled: bool) -> None:
    headers = ["Instruction class", "80386 target", "z386 0.1", "z386 current"]
    rows: list[list[str]] = []

    for result in results:
        current = min(result.samples) if result.samples else None
        baseline = Z386_01_MIN_CYCLES.get(result.name)
        current_text = fmt_cycles(current)
        if current is not None:
            current_text = colorize(current_text, classify_delta(current - result.target_cycles), color_enabled)
        rows.append([
            result.description,
            fmt_cycles(result.target_cycles),
            fmt_cycles(baseline),
            current_text,
        ])

    plain_rows = [
        [result.description, fmt_cycles(result.target_cycles), fmt_cycles(Z386_01_MIN_CYCLES.get(result.name)),
         fmt_cycles(min(result.samples) if result.samples else None)]
        for result in results
    ]
    widths = [
        max(len(headers[index]), *(len(row[index]) for row in plain_rows))
        for index in range(len(headers))
    ]

    print("Timing comparison (best-case cycles)")
    print(format_table_row(headers, widths))
    print("| " + " | ".join(["---"] + ["---:"] * (len(headers) - 1)) + " |")
    for row in rows:
        print(format_table_row(row, widths))
    print()


def use_color(mode: str) -> bool:
    if mode == "always":
        return True
    if mode == "never":
        return False
    return sys.stdout.isatty() and os.environ.get("TERM") not in (None, "", "dumb")


def classify_delta(delta: float | None) -> str:
    if delta is None:
        return "plain"
    if delta <= 0.0:
        return "good"
    if delta <= 1.0:
        return "warn"
    return "bad"


def colorize(text: str, level: str, enable: bool) -> str:
    if not enable or level == "plain":
        return text
    color = {
        "good": "\033[92m",
        "warn": "\033[93m",
        "bad": "\033[91m",
    }[level]
    return f"{color}{text}\033[0m"


def run_trace_generation(cycles_limit: int) -> Path:
    cmd = [
        sys.executable,
        "test_protected_mode.py",
        TEST_NAME,
        "--trace",
        "-c",
        str(cycles_limit),
    ]
    result = subprocess.run(
        cmd,
        cwd=TESTS_DIR,
        capture_output=True,
        text=True,
        timeout=180,
    )
    if result.returncode != 0:
        details = result.stdout.strip() or result.stderr.strip() or "unknown error"
        raise SystemExit(f"Trace generation failed: {details}")
    return DEFAULT_TRACE


def measure_steady_phase(phase: SteadyPhase, i_first_events: list[tuple[int, int]], cycle_period: float) -> list[float]:
    events = [(time, eip) for time, eip in i_first_events if eip in phase.eips]
    phase_index = {eip: idx for idx, eip in enumerate(phase.eips)}

    samples: list[float] = []
    for (time_a, eip_a), (time_b, eip_b) in zip(events, events[1:]):
        if phase_index[eip_b] == phase_index[eip_a] + 1:
            samples.append(cycles(time_b - time_a, cycle_period))

    # Measure the steady-state middle, not the edges.  386 microcode does not
    # overlap between instructions, so i_first->i_first is the true per-instruction
    # cost -- but the FIRST copy is unreliable (store-to-load forwarding from the
    # phase setup, or a cold-miss first touch) and the LAST borders the verify.
    # Drop one sample at each end so the reported cost is the warm steady state.
    if len(samples) >= 4:
        samples = samples[1:-1]
    return samples


def measure_branch_phase(
    phase: BranchPhase,
    i_first_events: list[tuple[int, int]],
    cycle_period: float,
    window_cycles: float,
) -> list[float]:
    branch_times = [time for time, eip in i_first_events if eip == phase.branch_eip]
    target_times = [time for time, eip in i_first_events if eip == phase.target_eip]
    max_gap = window_cycles * cycle_period

    samples: list[float] = []
    target_index = 0

    for branch_time in branch_times:
        while target_index < len(target_times) and target_times[target_index] <= branch_time:
            target_index += 1
        if target_index >= len(target_times):
            break

        target_time = target_times[target_index]
        if target_time - branch_time > max_gap:
            continue

        samples.append(cycles(target_time - branch_time, cycle_period))
        target_index += 1

    return samples


def main() -> int:
    parser = argparse.ArgumentParser(description="Measure instruction timing microbenchmark")
    parser.add_argument(
        "trace_file",
        nargs="?",
        default=str(DEFAULT_TRACE),
        help=f"Trace file to analyze (default: {DEFAULT_TRACE})",
    )
    parser.add_argument(
        "--run",
        action="store_true",
        help="Regenerate the instruction_timing trace before analysis",
    )
    parser.add_argument(
        "--cycles",
        type=int,
        default=20_000,
        help="Cycle limit when regenerating the trace (default: 20000)",
    )
    parser.add_argument(
        "--window-cycles",
        type=float,
        default=40.0,
        help="Maximum branch->target matching window in cycles (default: 40)",
    )
    parser.add_argument(
        "--color",
        choices=("auto", "always", "never"),
        default="auto",
        help="Colorize good/bad timing results (default: auto)",
    )
    args = parser.parse_args()

    trace_path = Path(args.trace_file)
    if args.run:
        trace_path = run_trace_generation(args.cycles)

    if not trace_path.exists():
        raise SystemExit(f"Trace file not found: {trace_path}")

    clk_rises, i_first_events = parse_trace(trace_path)
    cycle_period = infer_cycle_period(clk_rises)
    color_enabled = use_color(args.color)

    print(f"Trace: {trace_path}")
    print(f"Clock period: {cycle_period:.1f} ns")
    print()

    results: list[PhaseResult] = []

    for phase in STEADY_PHASES:
        samples = measure_steady_phase(phase, i_first_events, cycle_period)
        results.append(PhaseResult(phase.name, phase.description, phase.target_cycles, tuple(samples)))

    for phase in BRANCH_PHASES:
        samples = measure_branch_phase(phase, i_first_events, cycle_period, args.window_cycles)
        results.append(PhaseResult(phase.name, phase.description, phase.target_cycles, tuple(samples), branch=True))

    print_comparison_table(results, color_enabled)

    for result in results:
        samples = list(result.samples)
        avg = statistics.mean(samples) if samples else None
        delta = (avg - result.target_cycles) if avg is not None else None
        level = classify_delta(delta)
        delta_text = f"{delta:+.2f}" if result.branch and delta is not None else f"{delta:+.1f}" if delta is not None else "n/a"
        print(f"{result.name}: {result.description}")
        print(f"  target:  {result.target_cycles:.2f} cycles")
        print(f"  samples: {len(samples)}")
        measurement = "branch i_first -> target i_first" if result.branch else "i_first -> next i_first"
        print(
            f"  measured {measurement}: "
            f"{colorize(f'{summarize(samples)} cycles', level, color_enabled)}"
        )
        print(
            "  delta vs 386 target: "
            f"{colorize(f'{delta_text} cycles', level, color_enabled)}"
        )
        print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
